Student3MVC/Models/ErrorViewModel.cs
using System;

namespace Student3MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Student3MVC/Models/StudentContactInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Models
{
    public class StudentContactInfoViewModel
    {
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
    }
}

Student3MVC/Models/StudentEducationInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Models
{
    public class StudentEducationInfoViewModel
    {
        public string University { get; set; }
        public string Degree { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string Major { get; set; }
    }
}

Student3MVC/Models/StudentPersonalInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Models
{
    public class StudentPersonalInfoViewModel
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
    }
}

Student3MVC/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Models
{
    public class StudentViewModel
    {
        public int Id { get; set; }
        public StudentPersonalInfoViewModel StudentPersonalInfo { get; set; }
        public StudentEducationInfoViewModel StudentEducationInfo { get; set; }
        public StudentContactInfoViewModel StudentContactInfo { get; set; }
    }
}

Student3MVC/Models/Students.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Models
{
    static public class Students
    {
        static public List<StudentViewModel> All = new()
        {
            new()
            {
                Id = 3,
                StudentPersonalInfo = new()
                {
                    Age = 21,
                    Name = "Elchin",
                    Surname = "Babali"
                },
                StudentEducationInfo = new()
                {
                    University = "ASOIU",
                    Degree = "Bachelor",
                    Faculty = "FITM",
                    Department = "General and Applied Mathematics",
                    Major = "Computer Science"
                },
                StudentContactInfo = new()
                {
                    PhoneNumber = "00994557761921",
                    EmailAddress = "babalielchin@gmail.com"
                }
            },
            new()
            {
                Id = 17,
                StudentPersonalInfo = new()
                {
                    Age = 21,
                    Name = "Nijat",
                    Surname = "Tanriverdiyev"
                },
                StudentEducationInfo = new()
                {
                    University = "ASOIU",
                    Degree = "Bachelor",
                    Faculty = "FITM",
                    Department = "General and Applied Mathematics",
                    Major = "Computer Science"
                },
                StudentContactInfo = new()
                {
                    PhoneNumber = "null",
                    EmailAddress = "nijat.tanriverdiyev@gmail.com"
                }
            }
        };
    }
}

Student3MVC/Controllers/CreateController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Controllers
{
    public class CreateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

Student3MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Student3MVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Student3MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Students()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Student3MVC/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Student3MVC.Models;

namespace Student3MVC.Controllers
{
    public class StudentsController : Controller
    {
        private readonly List<StudentViewModel> _students = new()
        {
            new()
            {
                Id = 3,
                StudentPersonalInfo = new()
                {
                    Age = 21,
                    Name = "Elchin",
                    Surname = "Babali"
                },
                StudentEducationInfo = new()
                {
                    University = "ASOIU",
                    Degree = "Bachelor",
                    Faculty = "FITM",
                    Department = "General and Applied Mathematics",
                    Major = "Computer Science"
                },
                StudentContactInfo = new()
                {
                    PhoneNumber = "00994557761921",
                    EmailAddress = "babalielchin@gmail.com"
                }
            },
            new()
            {
                Id = 17,
                StudentPersonalInfo = new()
                {
                    Age = 21,
                    Name = "Nijat",
                    Surname = "Tanriverdiyev"
                },
                StudentEducationInfo = new()
                {
                    University = "ASOIU",
                    Degree = "Bachelor",
                    Faculty = "FITM",
                    Department = "General and Applied Mathematics",
                    Major = "Computer Science"
                },
                StudentContactInfo = new()
                {
                    PhoneNumber = "null",
                    EmailAddress = "nijat.tanriverdiyev@gmail.com"
                }
            }
        };
        public IActionResult Details(int id)
        {
            return View(Students.All.FirstOrDefault(student => student.Id == id));
        }
        public IActionResult Index()
        {
            return View(Students.All);
        }
    }
}

Student3MVC/Views/Create/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Student3MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Student3MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student3MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student3MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Student3MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Student3MVC/Views/Students/Details.cshtml
@model Student3MVC.Models.StudentViewModel 

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <div>
        <p>@Model.StudentPersonalInfo.Name @Model.StudentPersonalInfo.Surname, @Model.StudentPersonalInfo.Age </p>
        <p>@Model.StudentEducationInfo.University, @Model.StudentEducationInfo.Faculty, @Model.StudentEducationInfo.Department, @Model.StudentEducationInfo.Degree, @Model.StudentEducationInfo.Major</p>
        <p>@Model.StudentContactInfo.PhoneNumber, @Model.StudentContactInfo.EmailAddress</p>
    </div>
}

Student3MVC/Views/Students/Index.cshtml
@using Student3MVC.Models
@model List<StudentViewModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    foreach (StudentViewModel student in Model)
            {
                <div>
                    <p>Student Name: @student.StudentPersonalInfo.Name</p>
                    <p>Student Major: @student.StudentEducationInfo.Major</p>
                    <p>Student Email: @student.StudentContactInfo.EmailAddress</p>
                    <a asp-action="Details" asp-route-id="@student.Id">Details</a>
                </div>
            }

<form>
    <label for="id">Id:</label>
    <input type="text" id="id" name="id" required><br><br>

    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required><br><br>

    <label for="age">Age:</label>
    <input type="number" id="age" name="age" required><br><br>

    <label for="major">Major:</label>
    <input type="text" id="major" name="major" required><br><br>

    <input asp-controller="Create" asp-action="Index" type="submit" value="Create">
</form>
}